- name: Deploy nginx sites configuration
  template: 
    src: mysite.j2 
    dest: "/etc/nginx/sites-enabled/mysite"
  notify: restart nginx

#We delete default site
- name: Remove defaults
  file: 
    state: absent
    path: "/etc/nginx/sites-enabled/default"
  notify: restart nginx

