version: '3.7'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /home/dbartus/lvpersist/prometheus/persistance/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:rw
      - /home/dbartus/lvpersist/prometheus/persistance/conf/alerts.yml:/opt/bitnami/prometheus/conf/alerts.yml:rw
    networks:
      prometheus_network:
        aliases:
          - prometheus_host

volumes:
  schemas: {}
networks:
  prometheus_network:
    name: bridge_net
    driver: bridge
