Vagrant.configure("2") do |config|
  
  #------MULTIPLE VM MACHINES AT ONCE--------
  servers=[
    {
      :hostname => "red",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.50",
      :ssh_port => '2200'
    },
    {
      :hostname => "blue",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.51",
      :ssh_port => '2201'
    },
    {
      :hostname => "yellow",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.52",
      :ssh_port => '2202'
    }
  ]
  
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network :private_network, ip: machine[:ip]
          node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
          #------SHARED FOLDER------
          #Typical custom shared directory kinda VBox
          node.vm.synced_folder "~/Documents/wordpress", "/home/vagrant/wordpress"
          #------COPY FILE----------
          #To copy a file kind of nginx index file to a specific location inside Vagrant VM
          node.vm.provision "file", source: "/home/dbartus/demoProjects/vagrant4/index.html", destination: "/home/vagrant/index.html"
           #------CPU/MEMORY---------
          node.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1024]
            vb.customize ["modifyvm", :id, "--cpus", 1]
          end
    end
  end
  
end