Vagrant.configure("2") do |config|
    servers=[
      {
        :hostname => "monitoring",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.10.121",
        :ssh_port => '2210'
      },
      {
        :hostname => "dns",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.10.122",
        :ssh_port => '2211'
      },
      {
        :hostname => "web",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.10.123",
        :ssh_port => '2212'
      }
    ]
  
    servers.each do |machine|
  
      config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
      
        node.vm.network "public_network", bridge: "wlxd03745c49f09", ip: machine[:ip]
        #node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
  
        node.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--memory", 512]
          v.customize ["modifyvm", :id, "--cpus", 1]  
          v.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
      end
    end
  
  end