Vagrant.configure("2") do |config|
    servers=[
      {
        :hostname => "master",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.7.10",
        :ssh_port => '2210'
      },
      {
        :hostname => "web1",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.7.11",
        :ssh_port => '2211'
      },
      {
        :hostname => "web2",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.7.12",
        :ssh_port => '2212'
      },
      {
        :hostname => "db1",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.7.13",
        :ssh_port => '2213'
      },
      {
        :hostname => "loadbalancer",
        :box => "bento/ubuntu-18.04",
        :ip => "192.168.7.14",
        :ssh_port => '2214'
      }
    ]
  
    servers.each do |machine|
  
      config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
      
        node.vm.network :private_network, ip: machine[:ip]
        node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
  
        node.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--memory", 512]
          v.customize ["modifyvm", :id, "--cpus", 1]  
          v.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
      end
    end
  
  end