---
- name: Install bind9
  hosts: dns
  become: true
  tasks:

    - name: Update apt cache
      apt:
        name: update_cache 
        state: yes
        
    - name: Ensure bind9 is at the latest version
      apt:
        name: bind9
        state: latest

    - name: Write bind9 named.conf.local
      template:
        src: ../templates/named.conf.local
        dest: /etc/bind/named.conf.local
      #After we applyed new conf we restart bind9 with notify
      notify:
        - restart bind9

    - name: Write bind9 custom db file
      template:
        src: ../templates/db.cluster2
        dest: /etc/bind/db.cluster2

      #After we applyed new conf we restart bind9 with notify
      notify:
        - restart bind9

  #We need handler referencing notify "restart bind9" to apply module service and restart bind9 service
  handlers:
    - name: restart bind9
      service:
          name: bind9
          state: restarted