#wget https://github.com/prometheus/node_exporter/releases/download/v*/node_exporter-*.*-amd64.tar.gz
#tar xvfz node_exporter-*.*-amd64.tar.gz
#cd node_exporter-*.*-amd64
#./node_exporter
#https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-arm64.tar.gz

- name: Download node_exporter binary to local folder
  become: true
  get_url:
    url: "{{ node_exporter_url }}"
    dest: /tmp/node_exporter_amd64.tar.gz

- name: Unpack node_exporter binary
  become: true
  unarchive:
    src: /tmp/node_exporter_amd64.tar.gz
    dest: /tmp
    creates: /tmp/node_exporter


- name: Propagate node_exporter binaries
  
  copy:
    src: /tmp/node_exporter-1.4.0.linux-amd64/node_exporter
    dest: /bin/node_exporter
    mode: 0755
    owner: root
    group: root
  notify: restart node_exporter
  

- name: restart node_exporter
  become: true
  shell:
    cmd: sh /bin/node_exporter