- name: Modify resolv.conf file with custom DNS IP...
  lineinfile:
    dest: /etc/resolv.conf
    # The String to Search
    regexp: 'nameserver 127.0.0.53'
    # The String to Replace
    line: "nameserver 192.168.10.122"
    state: present
    #backup: yes


    